fix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: Build & Deploy MEAN App
+name: Build & Deploy MERN App
 
 on:
   push:
@@ -10,8 +10,16 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+     
       - name: Checkout
         uses: actions/checkout@v3
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ap-south-1
 
       - name: Login to DockerHub
         uses: docker/login-action@v2
@@ -21,13 +29,13 @@ jobs:
 
       - name: Build & Push Backend
         run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/mean-backend ./backend
-          docker push ${{ secrets.DOCKER_USERNAME }}/mean-backend
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest ./backend
+          docker push ${{ secrets.DOCKER_USERNAME }}/mern-backend:latest
 
       - name: Build & Push Frontend
         run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/mean-frontend ./frontend
-          docker push ${{ secrets.DOCKER_USERNAME }}/mean-frontend
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest ./frontend
+          docker push ${{ secrets.DOCKER_USERNAME }}/mern-frontend:latest
 
       - name: Setup SSH
         run: |
@@ -37,19 +45,27 @@ jobs:
 
       - name: Deploy to EC2
         run: |
-          ssh -o StrictHostKeyChecking=no ubuntu@$(aws ec2 describe-instances \
-            --filters "Name=tag:Name,Values=MEAN-DevOps-Server-Mumbai" \
+          EC2_IP=$(aws ec2 describe-instances \
+            --filters "Name=tag:Name,Values=MERN-DevOps-Server-Mumbai" \
             --query "Reservations[*].Instances[*].PublicIpAddress" \
-            --output text --region ap-south-1) << 'EOF'
+            --output text)
 
-          cd /home/ubuntu
-          if [ ! -d mean-app ]; then
-            git clone https://github.com/${{ github.repository }} mean-app
+          echo "EC2 IP: $EC2_IP"
+
+          if [ -z "$EC2_IP" ]; then
+            echo "EC2 IP not found!"
+            exit 1
           fi
-          cd mean-app
 
+          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP << EOF
+          cd /home/ubuntu
+
+          if [ ! -d mern-app ]; then
+            git clone https://github.com/${{ github.repository }} mern-app
+          fi
+
+          cd mern-app
           docker-compose pull
           docker-compose down
           docker-compose up -d
-
           EOF
